### ISSUE TITLE
TODO: Motivation - Auto add last 30 seconds

### ISSUE THREAD

**Issue by jameswberry** [jameswberry/workout-creator-cli#2]
TL;DR - TextEvent(s) of motivational prompts for the last 30s of an appropriately long block.

- [ ] New **Workout Detail** "Motivation30"
- [ ] Apply only to blocks of duration > 30s
- [ ] Default Prompts
  - [ ] "30 Seconds to go!"
  - [ ] "You can do it!"
  - [ ] "Keep Going!"
  - [ ] "All the way through!"

DETAILS:
