### ISSUE TITLE
TODO: Motivation - Full block

### ISSUE THREAD

**Issue by jameswberry** [jameswberry/workout-creator-cli#3]
TL;DR - TextEvent(s) of motivational prompts for full block duration.

- [ ] New **Workout Detail** "MotivationFull"
- [ ] Apply only to blocks of duration > 30s
- [ ] Default Prompts
  - [ ] "XXX Seconds to go!"
  - [ ] "Doing Great!"
  - [ ] "Keep it up!"
  - [ ] "Nice and Steady"
  - [ ] "Technique!"
  - [ ] "Go! Go! Go!"
- [ ] Override defaults with a compound Value in the CSV to be auto expanded into block Motivation TextEvents.
  - [ ] 100char max line length
  - [ ] ';' delimited

DETAILS:
