### ISSUE TITLE
TODO: Cadence Transitions

### ISSUE THREAD

**Issue by jameswberry** [jameswberry/workout-creator-cli#5]
TL;DR - Add TextEvent(s) for cadence transitions _**within**_ a block.

- [ ] New Workout Detail "CadenceTransitions"
- For block _Types_ that support multiple cadence transitions (IntervalsT, etc.)
  - [ ] Determine cadence transition {{offset}}s.
  - [ ] Determine {{transition_cadence}}.
  - [ ] Determine transitions {{direction}} (Up or Down)
- [ ] Add TextEvent to current block.
  - _Message_: "Bring cadence {{direction}} to {{transition_cadence}}."
  - _Offset_: {{offset}}

DETAILS:
