### ISSUE TITLE
TODO: Cadence transitions between blocks

### ISSUE THREAD

**Issue by jameswberry** [jameswberry/workout-creator-cli#6]
TL;DR - Add TextEvent(s) for cadence transitions _**between**_ blocks.

- [ ] New Workout Detail "PreemptiveCadenceTransitions"
- [ ] Determine cadence transitions between adjacent blocks
- [ ] Determine {{transition cadence}}
- [ ] Determine transitions {{direction}} (Up or Down)
- [ ] Add TextEvent to preceding block.
  - _Message_: "Bring cadence {{direction}} to {{transition_cadence}}."
  - _Offset_: {{duration}}-10

DETAILS:
